[workspace]
members = [
    "python",
    "rust/ffi/node",
    "rust/vectordb"
]
resolver = "2"

[workspace.dependencies]
lance = "=0.6.5"
# Note that this one does not include pyarrow
arrow = { version = "43.0.0", optional = false }
arrow-array = "43.0"
arrow-data = "43.0"
arrow-schema = "43.0"
arrow-ipc = "43.0"
half = { "version" = "=2.2.1", default-features = false }
object_store = "0.6.1"
snafu = "0.7.4"
