name: Create release commit

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (create the local commit/tags but do not push it)'
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
      part:
        description: 'What kind of release is this?'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0
          lfs: true
      - name: Set git configs for bumpversion
        shell: bash
        run: |
          git config user.name 'Lance Release'
          git config user.email 'lance-dev@lancedb.com'
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install tools
        run: |
          pip install bump2version
          cargo install cargo-edit
      - name: Bump version, create tag and commit
        run: |
          export CURRENT_VERSION=`cat VERSION`
          bumpversion --verbose ${{ inputs.part }}
          export NEW_VERSION=`cat VERSION`
          cargo set-version $NEW_VERSION
          jq --arg ver "$NEW_VERSION" '
            .version = $ver |
            .optionalDependencies["@lancedb/vectordb-darwin-arm64"] = $ver |
            .optionalDependencies["@lancedb/vectordb-darwin-x64"] = $ver |
            .optionalDependencies["@lancedb/vectordb-linux-arm64-gnu"] = $ver |
            .optionalDependencies["@lancedb/vectordb-linux-x64-gnu"] = $ver |
            .optionalDependencies["@lancedb/vectordb-win32-x64-msvc"] = $ver' node/package.json > temp.json && mv temp.json node/package.json
          git add node/package.json rust/ffi/node/Cargo.toml rust/vectordb/Cargo.toml VERSION .bumpversion.cfg
          git commit -m "Bump version: $CURRENT_VERSION → $NEW_VERSION"
      - name: Push new version and tag
        if: ${{ inputs.dry_run }} == "false"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.LANCEDB_RELEASE_TOKEN }}
          branch: main
          tags: true
      - uses: ./.github/workflows/update_package_lock
        if: ${{ inputs.dry_run }} == "false"
        with:
          github_token: ${{ secrets.LANCEDB_RELEASE_TOKEN }}

