name: Python

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - python/**
      - .github/workflows/python.yml
jobs:
  lint:
    timeout-minutes: 30
    runs-on: "ubuntu-22.04"
    defaults:
      run:
        shell: bash
        working-directory: python
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: python
    - name: Install linting tools
      run: |
        pip install black isort ruff maturin
        sudo apt update
        sudo apt install -y protobuf-compiler libssl-dev
    - name: Lint Rust
      run: |
        cargo fmt -- --check
        cargo clippy --all-features --tests -- -D warnings
    - name: Lint Python
      run: |
        black --check lancedb tests
        isort --check-only lancedb tests
        # ruff check lancedb tests
  doctest:
    timeout-minutes: 30
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash
        working-directory: python
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y protobuf-compiler libssl-dev
        pip install maturin
    - name: Run doctest
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install tantivy@git+https://github.com/quickwit-oss/tantivy-py#164adc87e1a033117001cf70e38c82a53014d985
        maturin develop --extras tests
        pytest --doctest-modules lancedb
  linux:
    timeout-minutes: 30
    strategy:
      matrix:
        python-minor-version: [ "8", "9", "10", "11" ]
    runs-on: "ubuntu-22.04"
    defaults:
      run:
        shell: bash
        working-directory: python
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.${{ matrix.python-minor-version }}
    - uses: ./.github/workflows/build_linux_wheel
    - name: Install lancedb
      run: |
        pip install $(ls target/wheels/lancedb-*.whl)[tests,dev]
        pip install tantivy@git+https://github.com/quickwit-oss/tantivy-py#164adc87e1a033117001cf70e38c82a53014d985
    - name: Run tests
      run: pytest -x -v --durations=30 tests
  mac:
    timeout-minutes: 30
    runs-on: "macos-12"
    defaults:
      run:
        shell: bash
        working-directory: python
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install macos dependency
      shell: bash
      run: |
        brew install protobuf
    - uses: PyO3/maturin-action@v1
      with:
        command: build
        working-directory: python
    - name: Install lancedb
      run: |
        pip install $(ls target/wheels/lancedb-*.whl)[tests,dev]
        pip install tantivy@git+https://github.com/quickwit-oss/tantivy-py#164adc87e1a033117001cf70e38c82a53014d985
    - name: Run tests
      run: pytest -x -v --durations=30 tests
